
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /run/nginx.pid;


events {
	worker_connections  1024;
}

http {
	include       /etc/nginx/mime.types;
	default_type  application/octet-stream;

	log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
					'$status $body_bytes_sent "$http_referer" '
					'"$http_user_agent" "$http_x_forwarded_for"';

	access_log  /var/log/nginx/access.log  main;

	sendfile        on;
	#tcp_nopush     on;

	keepalive_timeout  6500;

	#gzip  on;

	# Specify the different Servers you want to have listening
	server {

		# Port will be set by Dockerfile envsubst on buildtime
		listen				$NGINX_PORT;
		root				/nginx;
		index				index.html index.htm;

		client_max_body_size 500M;
		error_page 404		/errors/404.html;

		# Root
		location / {
			proxy_pass			http://nextjs:$NEXTJS_PORT;
			proxy_set_header	Host $host;
			proxy_set_header	X-Real-IP $remote_addr;
			proxy_set_header	X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header	X-Forwarded-Proto $scheme;
		}

		# WebSocket / Socket.io support
        location /socket.io/ {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;

            # This must point to your NestJS service name and its internal port
            # Assuming your docker service is named 'nestjs-api'
            proxy_pass http://nestjs:$NESTJS_PORT;

            # These three lines enable the WebSocket protocol upgrade
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            # Disable caching for the proxy
            proxy_cache_bypass $http_upgrade;
        }

		# Just needed, so Servers stop complaining about it
		location = /favicon.ico {
			log_not_found off;
			access_log off;
		}
		# Html pages
		location /health {
			access_log off;
            add_header 'Content-Type' 'application/json';
            return 200 '{"status":"UP"}';
		}

		location /static {
			root			/nginx;
			index			index.html;
		}

		location /errors {
			root			/nginx;
			index			404.html;
		}
    }
}