
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /run/nginx.pid;


events {
	worker_connections  1024;
}

http {
	include       /etc/nginx/mime.types;
	default_type  application/octet-stream;

	log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
					'$status $body_bytes_sent "$http_referer" '
					'"$http_user_agent" "$http_x_forwarded_for"';

	access_log  /var/log/nginx/access.log  main;

	sendfile        on;
	#tcp_nopush     on;

	keepalive_timeout  6500;

	#gzip  on;

	# Specify the different Servers you want to have listening
	server {

		# Port will be set by Dockerfile envsubst on buildtime
		listen				$NEXTJS_PORT;
		root				/nextjs;
		index				index.html index.htm;

		client_max_body_size 500M;
		error_page 404		/errors/404.html;

		# Root
		location / {
			root			/nextjs;
			index			index.html;
		}
		# Just needed, so Servers stop complaining about it
		location = /favicon.ico {
			log_not_found off;
			access_log off;
		}
		# Html pages
		location /dashboard {
			root			/nextjs;
			index			index.html;
		}
    }
}