/** @type {import('next').NextConfig} */
const nextConfig = {
  async rewrites() {
    return [
      {
        source: "/game",
        destination: "http://nestjs:$NESTJS_PORT/game",
      },
      {
        source: "/gamefiles/:path*",
        destination: "http://nestjs:$NESTJS_PORT/gamefiles/:path*",
      },
      {
        source: "/api/:path*",
        destination: "http://nestjs:$NESTJS_PORT/api/:path*",
      },
    ];
  },
};

module.exports = nextConfig;

// Generated by AI